apiVersion: polaris.synthesis.co.za/v1alpha1
kind: PolarisContainerRegistry
metadata:
  name: {{ template "thischart.fullname" $ }}
  labels:
    polaris-project: rev
    polaris-component: createtopics
    app: {{ template "thischart.name" $ }}
    chart: {{ template "thischart.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
spec:
  name: rev-createtopics